version: "3.7"

services:
  catalyst: &catalyst
    build:
      context: .
      dockerfile: .docker/catalyst/Dockerfile
    volumes:
      - .:/catalyst
      - bundler_gems:/usr/local/bundle
    depends_on:
      - solr
      - db
      - horizon_holding_info
      - webpack
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - SOLR_PORT=8983
      - SOLR_URL=http://solr:8983/solr/blacklight-core
      - MYSQL_SERVER=db
      - MYSQL_DATABASE=catalyst
      - MYSQL_USER=catalyst
      - MYSQL_PASSWORD=catalyst
      - MYSQL_PORT=3306
      - FLIPPER_USERNAME=flipper
      - AEON_URL=https://aeon.library.jhu.edu
      - FLIPPER_PASSWORD=flipper
      - BORROW_DIRECT_HOST=bdtest.relaisd2d.com
      - ILLIAD_URL=https://ill.library.jhu.edu/msel/illiad.dll
      - RELAIS_API_URL=borrow-direct.relais-host.com
      - "RELAIS_API_KEY=${RELAIS_API_KEY}"
      - RELAIS_PARTNERSHIP_ID=BD
      - RELAIS_LIBRARY_SYMBOL=JOHNSHOPKINS
      - "RELAIS_PATRON_ID=${RELAIS_PATRON_ID}"
      - CATALYST_UMLAUT_BASE_URL=https://findit.library.jhu.edu
      - HORIZON_WS_URL=http://horizon_holding_info:8080/ws
      - GOOGLE_BOOKS_API_KEY="${GOOGLE_BOOKS_API_KEY}"
      - SECRET_KEY_BASE="${SECRET_KEY_BASE}"
      - SFX_BASE_URL="https://sfx-stage.library.jhu.edu/sfxlcl41"
      - WEBPACKER_DEV_SERVER_HOST=webpack
  webpack:
    <<: *catalyst
    command: ./bin/webpack-dev-server
    depends_on:
      - db
      - solr
    ports:
      - 3035:3035


  solr:
    image: "ghcr.io/jhu-library-applications/catalyst-docker-solr"
    ports:
      - "8983:8983"
    volumes:
      - solr:/var/solr/data
  horizon_holding_info:
    image: "ghcr.io/jhu-library-applications/horizon-holding-info-servlet"
    ports:
      - "8080:8080" 
  db:
    image: mariadb:10.2
    environment:
      MYSQL_USER: catalyst
      MYSQL_DATABASE: catalyst
      MYSQL_PASSWORD: catalyst
      MYSQL_ROOT_PASSWORD: catalyst
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  bundler_gems:
  solr:
  db:
