version: "3.7"

services:
  catalyst: &catalyst
    build:
      context: .
      dockerfile: .docker/catalyst/Dockerfile
    volumes:
      - .:/catalyst
      - bundler_gems:/usr/local/bundle
    depends_on:
      - solr
      - db
      - horizon_holding_info
    tty: true
    stdin_open: true
    restart: always
    shm_size: "1g"  
    ports:
      - "3000:3000"
    env_file: .env.development
    networks:    
      - internal_network
      - external_network 
  webpack:
    <<: *catalyst
    command: ./bin/webpack-dev-server
    depends_on:
      - catalyst
      - db
      - solr
    ports:
      - 3035:3035
    networks: 
      - internal_network 

  solr:
    shm_size: "1g"
    image: "ghcr.io/jhu-library-applications/catalyst-docker-solr"
    restart: always
    env_file: .env.development
    ports:
      - "8983:8983"
    volumes:
      - solr:/var/solr/data
    networks: 
      - internal_network 
  horizon_holding_info:
    image: "ghcr.io/jhu-library-applications/horizon-holding-info-servlet"
    ports:
      - "8080:8080"
    networks: 
      - internal_network
      - external_network # Needs internet access to build 
  db:
    shm_size: "256m"
    image: mariadb:10.2
    restart: always
    env_file: .env.development
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks: 
      - internal_network
volumes:
  bundler_gems:
  solr:
  db:
networks:
  external_network:
  internal_network:
    internal: true
