emsel:
  library: SPECCOLLJHU
elscsp:
  library: SPECCOLLJHU
elsc:
  library: SPECCOLLJHU
epbdy:
  library: PEABODYJHU
egar:
  library: GARRETTJHU
collections:
 - ecageki
 - ecircag
 - egtrade
 - ehinkbl
 - ehinkes
 - eocirmr
 - eofarrf
 - eofart
 - eofdcg
 - eofgpl
 - eofgplm
 - eofhseb
 - eofhser
 - eofhtlr
 - eofmdbl
 - eofmed
 - eofmeda
 - eofmedg
 - eofmedt
 - eofmrta
 - eofms
 - eofpam
 - eofpama
 - eofprbl
 - eofpro
 - eofspbi
 - eofspbl
 - eofspec
 - eofsptb
 - eofsptu
 - eofzioc
 - eofzion
 - esacq
 - esarc
 - esarck
 - esarcrf
 - esbirny
 - escagbl
 - escage
 - escaggi
 - esfor
 - esforbl
 - esfwlbl
 - esfwlr
 - esg2f
 - esg2fbl
 - esgnl
 - esgnlbl
 - esgnlf
 - esgpbg
 - esgpby
 - esgpdi
 - esgpfo
 - esgpfom
 - esgpind
 - esgpmen
 - esgptm
 - esgpyr
 - esgrbl
 - esgrf
 - esgrfbl
 - esgrr
 - esgrrbl
 - esgrt
 - eshtlr
 - esmac
 - esmanu
 - esmchn
 - esmchnr
 - esmed
 - esmedbl
 - espugib
 - espugin
 - esref
 - esrosen
 - estudbl
 - estudor
 - egdiss
 - egdissa
 - egdissb
 - egess
 - eoclabl
 - eoclass
 - eofdia
 - eofdib
 - eofdidc
 - eofdisa
 - eofdiss
 - eofdits
 - eoschae
 - eoschbl
 - eostmr
 - esgmap
 - esgpam
 - esgpfgp
 - esgpgr
 - esgpmf
 - esgpms
 - esgprf
 - esgri
 - esgribl
 - esgrtbl
 - esgrtms



