# GitHub Actions for the release event

name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ github.event.release.tag_name }}"
        echo "${{ github.event.release.name }}"
        echo "${{ github.event.release.body }}"
    - name: Notify release to Slack
      uses: lizefield/notify-release-to-slack@v1.0
      with:
        slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
        releaseMessage: ${{ github.event.release.body }}
