name: Run the tests

on: push
env:
  # these are all referenced in our app's database.yml for test
  # FindIt needs to be the actual prod url because it is loaded
  # on pages when the capybara tests are loaded.
  MYSQL_SERVER: db
  MYSQL_DATABASE: catalyst
  MYSQL_USER: catalyst
  MYSQL_PASSWORD: catalyst
  FLIPPER_USERNAME: flipper
  FLIPPER_PASSWORD: flipper
  SOLR_URL: http://solr:8983/solr/blacklight-core
  CATALYST_UMLAUT_BASE_URL: https://findit.library.jhu.edu
  AEON_URL: https://aeon.library.jhu.edu
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  GOOGLE_BOOKS_API_KEY: ${{ secrets.GOOGLE_BOOKS_API_KEY }}
  HORIZON_WS_URL: http://horizon_holding_info:8080/ws
  EZPROXY_PREFIX: "http://proxy1.library.jhu.edu/login?url="
  SFX_BASE_URL: "https://sfx.library.jhu.edu/sfxlcl41"
  ILLIAD_URL: https://ill.library.jhu.edu/msel/illiad.dll
  RELAIS_API_URL: borrow-direct.relais-host.com
  RELAIS_API_KEY: ${{ secrets.RELAIS_API_KEY }}
  RELAIS_PARTNERSHIP_ID: BD
  RELAIS_LIBRARY_SYMBOL: JOHNSHOPKINS
  RELAIS_PATRON_ID: ${{ secrets.RELAIS_PATRON_ID }}
  GITHUB_TOKEN: ${{ github.token }}
  WEBPACKER_DEV_SERVER_HOST: webpack
jobs:
  compose-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Run the tests with the Makefile
        run: make test 
        
      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: tmp/screenshots
  compose-test-system:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Run the system tests with the Makefile
        run: make test-system 
        
      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: tmp/screenshots
